version: '2'

services:
  imaginarium:
    depends_on:
      - mysql
    networks:
      - imaginarium-net

  mysql:
    image: mysql:5.7
    networks:
      - imaginarium-net
    ports:
      - 3306:3306
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
      - --skip-character-set-client-handshake
    environment:
      - MYSQL_ROOT_PASSWORD=imaginarium_pass
      - MYSQL_DATABASE=imaginarium_db
      - MYSQL_USER=imaginarium_user
      - MYSQL_PASSWORD=imaginarium_pass

networks:
  imaginarium-net: {}
