version: '2'

services:
  imaginarium:
    build: .
    command: python manage.py runserver
    volumes:
      - .:/opt/:rw
    networks:
      - imaginarium-external

networks:
  imaginarium-external:
    external: true
